name: Larastan (PHPStan for Laravel)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  larastan:
    name: Run Larastan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2  # Adjust according to your package support
          tools: composer
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Larastan (PHPStan)
        run: ./vendor/bin/phpstan analyse
